### ISSUE TITLE
double {{ and }} are also parsed but always empty

### ISSUE THREAD

**Issue by AndreasA** [TYPO3/Fluid#213] opened 2016-10-27 06:11 UTC
When using for instance:
{{settings.foo}}

it is also parsed but basically always empty.
It would be nice if that would retrieve the value of  settings.if and then uses that string to retrieve the value of the name.
For instance, if settings.foo is bar, and bar is 123, then the output should be 123.
That way dynamic array access would also be possible.

Furthermore, there should be an option to disable the parsing of double {{ expressions as some javascript templates like handlebars use those to evaluate expressions and it makes it complicated to output such a template inside fluid. But normal { should still be resolved.
In theory one can create an interceptor for that but it is unnecessary complex.

**Comment by NamelessCoder** [comment] 2016-11-02 01:29
I've added an example and functional test to prove that this method for variable access is in fact already supported. It's possible you face another issue which makes the value of `settings.foo` (in the text you also mention `settings.if` so there does seem to be some confusion?).

> That way dynamic array access would also be possible.

This is already supported; see examples.

> Furthermore, there should be an option to disable the parsing of double {{ expressions

There is - wrap with CDATA and the expressions will not be parsed as Fluid.

**Comment by AndreasA** [comment] 2016-11-02 13:41
This:
```
<f:alias map="{foo: 'Hello World', bar: 'o'}">
		#{f{bar}o}#
	</f:alias>
```

results in "##" being outputed instead of "#Hello World#" as the example would suggest.

Or if I use f:debug instead it results in NULL. Using the current TYPO3 CMS master with composer install to test this.

In regards to CDATA:
<f:debug><![CDATA[{f{bar}o}]></f:debug>

results in 
'<![CDATA[]>' (11 chars)

instead of {f{bar}o}

What works is using  <![CDATA[{]>f{bar}o}

which then results in '{foo}' .
However, I then have to use CDATA per { and per value which makes wirting the template way more compley then it has to be.

**Comment by NamelessCoder** [comment] 2016-11-02 14:32
Shell output log from my test:

```
macbook:TYPO3.Fluid claus$ ./bin/fluid
<f:alias map="{foo: 'Hello World', bar: 'o'}">
        #{f{bar}o}#
    </f:alias>
^D
        #Hello World#
```

I still can't reproduce your issue, Travis can't reproduce it either on any PHP version. Are you absolutely certain you are using the Fluid standalone engine...?

**Comment by NamelessCoder** [comment] 2016-11-02 14:37
NB: if you need to test some quick and dirty Fluid, use `./vendor/bin/fluid` in your framework (I ran this from the repository itself, hence `./bin/fluid` above). It enters an interactive shell where you type all the Fluid you want executed, then press `CTRL-D` to execute it.

**Comment by AndreasA** [comment] 2016-11-02 15:06
OK. In regards to CDATA I can also verify it with ./bin/fluid

In regards to the example above:
1.) It works with ./bin/fluid
2.) It fails in TYPO3 CMS current master with dev-master of typo3fluid/fluid
2.b) The issue seems to be the following:
$this->setVariableProvider($objectManager->get(CmsVariableProvider::class));

If I use 
$this->setVariableProvider($objectManager->get(StandardVariableProvider::class));

it works also in TYPO3 CMS. Should I create a bug report for TYPO3 or will you take care of it?

**Comment by NamelessCoder** [comment] 2016-11-02 15:08
Please create a bug report for TYPO3 - I'm not sure I will be the one to handle it!

In any case, good to finally pin down the source of the problem. Closing this issue.

**Closed by NamelessCoder** 2016-11-02 15:08 UTC
