### ISSUE TITLE
Make parent sections available

### ISSUE THREAD

**Issue by cedricziel** [TYPO3/Fluid#358] opened 2017-12-15 12:32 UTC
Twig allows rendering parent blocks:

```jinja
{% block foo %}
  {{ parent() }}
{% endblock %}
```

Can we have something like that?

**Comment by NamelessCoder** [comment] 2017-12-15 13:02
I kind of have a PoC for that (f:sections to import sections from named partial, you can then render and/or override them locally) but because it's the "wrong way" in the internals (going up rather than down the tree) and sections are currently transferred in a pretty oldschool way, it's quickly become a huge change with several internally breaking changes leading up to it.

TL;DR: yes, but it will require at least another week of work even though I have a working demo of it; sponsoring would help a lot.

**Comment by lolli42** [comment] 2023-05-10 22:47
Hey.

I hope it's ok to close here with "not planned" for now: The fluid v3 approach did not make it, and there is currently no work to change the fluid syntax accordingly. The issue is of course kept in history, but it's unclear if and how Fluid may catch up on this.

**Closed by lolli42** 2023-05-10 22:47 UTC
