### ISSUE TITLE
Cannot set $contentArgumentName using CompileWithContentArgumentAndRenderStatic trait

### ISSUE THREAD

**Issue by mbrodala** [TYPO3/Fluid#387] opened 2018-05-23 15:11 UTC
The docs for the `CompileWithContentArgumentAndRenderStatic` trait indicate that one should set the `$contentArgumentName` property to select a particular argument instead of relying on automatic resolving.

However, the naive approach by directly setting the property value does not work since one cannot redefine properties provided by a trait. It would be necessary to remove the property from the trait to allow this.

Alternatively one could do this in the constructor or in the `initialize()` method. If that's the way to go we should probably mention this explicitly.

What do you think?

**Comment by NamelessCoder** [comment] 2018-05-23 16:20
The docs and parts of the implementation are both wrong here and probably got mixed up during development when this was temporarily on the base class and not a trait. Adjusting the docs to recommend overriding `resolveContentArgumentName` method to return a hardcoded string would solve the immediate problem.

Long-term we can consider removing the property from the trait but this does mean we need to check if it is set, and that it won't appear in your IDE like `escapeOutput` for example does. Either that, or we simply merge the trait into the abstract VH class and make it opt-in so you have to override `protected $contentArgumentName = 'myArgument';` to activate it. Then the trait can be left in place and used as compatibility.

IMHO a content argument is so frequently used it will be fine as part of any VH base code - as long as it only triggers when you opt in.

Obviously the `resolveContentArgumentName` method would then need to be merged into the abstract VH class as well so we have a method we can override with the trait to reproduce the current logic. We can even keep the trait (but remove the property it contains) indefinitely since it and the base class' methods will be, I predict, identical.

**Comment by lolli42** [comment] 2022-07-27 13:26
We took care of this in #583 and improved the property comment to clarify how it should be used.

**Closed by lolli42** 2022-07-27 13:26 UTC
