### ISSUE TITLE
[BUG] ConditionViewHelper inline - children content (then/else) executed before condition is resolved

### ISSUE THREAD

**Issue by AndreasA** [TYPO3/Fluid#350] opened 2017-12-04 10:26 UTC
If one uses a ConditionViewHelper inline then the content of then and else is executed before the condition is resolved.
This might be a problem if one needs to check if a value exists before executing a certain ViewHelper which might otherwise result in an exception,
e.g. then using ./bin/fluid and enters:

```
<f:alias map="{notTrueValue: 0}">
{f:if(condition: notTrueValue, then: '{f:render(section: \'content\')}', else: 'bar')}
</f:alias>
```

It will fail although notTrueValue = 0 which should result in bar being rendered.
I only used the render ViewHelper as an example to produce an exception. 
In reality it might be to check in TYPO3 if an image exists and only execute the ImageViewHelper then.

However, the following works fine:
```
<f:alias map="{notTrueValue: 0}">
<f:if condition="{notTrueValue}">
<f:then>{f:render(section: 'content')}</f:then>
<f:else>bar</f:else>
</f:if>
</f:alias>
```

**Comment by NamelessCoder** [comment] 2017-12-05 22:18
This is true for *any and all ViewHelper arguments*. They will always be evaluated before calling the ViewHelper - or the arguments array would not contain the values you need.

When you expand the expression to use nodes, those get *parsed but not evaluated until the ViewHelper starts rendering*. Internally, this creates closures for child nodes and evaluates those after it has evaluated the condition itself.

This is, in other words, by design.

By the way, conditional rendering of a section or partial is most efficient if done like this:

```xml
{f:render(section: 'foo') -> f:if(condition: something)}
```

**Comment by AndreasA** [comment] 2017-12-06 06:44
OK. Your scenario works and ensures "f:render" is only executed if the condition is true.
Which will probably make it the best for "if" checks in inline notation as it doesn't executed the sub ViewHelpers.

However, what if I also need an else branch? I thought about Ternary expression but that one doesn't seem to support ViewHelpers in the then / else branches? Also I would have to define the value for else first as I cannot use strings directly there.

From what I tested something like this won't work (it isn't even executed):
```
<f:alias map="{something: 0, other: 'test'}">
{f:render(section: 'foo') -> f:then() -> other -> f:else() -> f:if(condition: something)}
</f:alias>
```

**Comment by NamelessCoder** [comment] 2018-01-01 03:04
It is, I'm sorry to say, not possible to create two same-level child nodes with inline syntax. At least not with the standard Fluid components. The only way to achieve what you sketched would be to create a different condition ViewHelper base class which instead of looking for `f:then` and `f:else`, looks through the entire chain to locate `f:then` and `f:else` which are not nested in another condition ViewHelper. Normally such nesting would also trigger an exception - so you would need to create custom `f:then` and `f:else` ViewHelpers as well (if I remember the API correctly).

It is so counter to the design of the inline syntax that I would personally say you shouldn't attempt this sort of integration. Instead, you will have to create two separate inline chains where one only triggers on the true condition and the other only triggers when false.

Will close this issue as "works as intended, by design".

**Closed by NamelessCoder** 2018-01-01 03:04 UTC

**Comment by AndreasA** [comment] 2018-01-03 08:09
OK. Thanks for your feedback. So the best way would be: 
```
{f:render(section: 'fooForTrue') -> f:if(condition: something)}{f:render(section: 'fooForFalse') -> f:if(condition: '!({something})')}
```
Or something like this if I need then and else with inline notation.
