### ISSUE TITLE
Different results of template parser for arrays on different operating systems

### ISSUE THREAD

**Issue by dlubitz** [TYPO3/Fluid#449] opened 2019-05-02 09:34 UTC
I had issues with shorthand viewhelpers. The arguments I passed as an array where handled as a string at the end. I dug deeper into the issue and found the root cause in the regex `\TYPO3Fluid\Fluid\Core\Parser\Patterns::$SPLIT_PATTERN_SHORTHANDSYNTAX_ARRAY_PARTS` for splitting the arrays recusive. 

My viewhelper code: 
```
{f:translate(id: 'some.id.to.translate', package: 'Vendor.Package', arguments: {0: some.value})}
``` 
which leads to the exeption: 
```
The argument "arguments" was registered with type "array", but is of type "string" in view helper
```

**I could reproduce** this error **just on a FreeBSD** server and could find related bug reports.

Related issues: 
- https://forge.typo3.org/issues/87958
- https://forge.typo3.org/issues/87573

---
The [regex pattern](https://github.com/TYPO3/Fluid/blob/dbe74a61ba1d67f7d957e714ab42273511813987/src/Core/Parser/Patterns.php#L231) fetches there for any reason `VariableIdentifier` and `Subarray`. Which leads to the issue described above, because the Subarray gets handled as ObjectAccessorNode.

https://github.com/TYPO3/Fluid/blob/bcd0ff44dd3c4f9d0f37097b0237db6319c2b181/src/Core/Parser/TemplateParser.php#L688-L698

### Test code
```
$string = 'id: \'some.id.to.translate\', package: \'Vendor.Package\', arguments: {0: some.value}';
preg_match_all(\TYPO3Fluid\Fluid\Core\Parser\Patterns::$SPLIT_PATTERN_SHORTHANDSYNTAX_ARRAY_PARTS, $string, $matches, PREG_SET_ORDER);
print_r($matches);
```
### Expected result:
```
Array
(
    [0] => Array
        (
            [0] => id: 'some.id.to.translate'
            [ArrayPart] => id: 'some.id.to.translate'
            [1] => id: 'some.id.to.translate'
            [Key] => id
            [2] => id
            [QuotedString] => 'some.id.to.translate'
            [3] => 'some.id.to.translate'
        )

    [1] => Array
        (
            [0] => package: 'Vendor.Package'
            [ArrayPart] => package: 'Vendor.Package'
            [1] => package: 'Vendor.Package'
            [Key] => package
            [2] => package
            [QuotedString] => 'Vendor.Package'
            [3] => 'Vendor.Package'
        )

    [2] => Array
        (
            [0] => arguments: {0: some.value}
            [ArrayPart] => arguments: {0: some.value}
            [1] => arguments: {0: some.value}
            [Key] => arguments
            [2] => arguments
            [QuotedString] =>
            [3] =>
            [VariableIdentifier] =>
            [4] =>
            [Number] =>
            [5] =>
            [Subarray] => 0: some.value
            [6] => 0: some.value
        )

)
```

### Wrong result:
```
Array
(
    [0] => Array
        (
            [0] => id: 'some.id.to.translate'
            [ArrayPart] => id: 'some.id.to.translate'
            [1] => id: 'some.id.to.translate'
            [Key] => id
            [2] => id
            [QuotedString] => 'some.id.to.translate'
            [3] => 'some.id.to.translate'
        )

    [1] => Array
        (
            [0] => package: 'Vendor.Package'
            [ArrayPart] => package: 'Vendor.Package'
            [1] => package: 'Vendor.Package'
            [Key] => package
            [2] => package
            [QuotedString] => 'Vendor.Package'
            [3] => 'Vendor.Package'
        )

    [2] => Array
        (
            [0] => arguments: {0: some.value}
            [ArrayPart] => arguments: {0: some.value}
            [1] => arguments: {0: some.value}
            [Key] => arguments
            [2] => arguments
            [QuotedString] =>
            [3] =>
            [VariableIdentifier] => some.value
            [4] => some.value
            [Number] =>
            [5] =>
            [Subarray] => 0: some.value
            [6] => 0: some.value
        )

)
```

These values should be empty:
```
    [2] => Array
        (
            ...
            [VariableIdentifier] => some.value
            [4] => some.value
            ...
```

### Tested environments:
- Ubuntu 16.04.6 LTS (Xenial Xerus), PHP7.3: _expected result_ 
- CentOS release 6.10 (Final): _expected result_ 
- Windows 10 Subsystem Linux / Ubuntu, PHP 7.3: _expected result_ 
- **FreeBSD 11.2-RELEASE-p9 #7 r344427, PHP7.3: _wrong result_**

I'm not sure how to solve this issue in Fluid, but maybe the regex could become more strict or optimized to behave equal on all systems.

**Comment by NamelessCoder** [comment] 2019-05-02 12:53
Oh boy, regular expressions come back to bite us again. Thanks for the very detailed reports and testing, @dlubitz - that's extremely appreciated!

We had a similar issue a while back with older PHP versions and now-outdated versions of linked preg libraries. If I recall (it's been many years) it was also a problem with the named patterns and recursion.

And more recently we discovered that preg has an internal limitation on the size of matches when doing recursive matches - which we cannot change. This one prevents you from declaring large arrays - at some point, Fluid starts seeing the array as a string due to the limit.

I believe the only good way to move forward is to abandon the use of regular expressions, at least for this complex recursive matching, in favor of some more naive (tokenisation-like) procedures that recursively split and tokenise Fluid templates then creates the syntax tree from those.

There is progress being made in this department but unfortunately it's very far from easy to do this right, without causing significant performance impacts. I'm at my 4th attempt using a mix of naive string searches and splits without requiring multiple stacks during parsing, plus making nodes in the syntax tree more interchangeable so they don't necessarily need to "know" what type of node they are until all tokens have been collected.

If you have some experience with similar things and would like to involve yourself you would be more than welcome!

**Comment by dlubitz** [comment] 2019-05-02 13:56
> If you have some experience with similar things and would like to involve yourself you would be more than welcome!

Sorry, I I'm not that experienced with parsing/tokenizing. :/

**Comment by jonnitto** [comment] 2019-08-19 09:31
Does the translate view helper work with the tag annotation `<f:translate />` on BSD?

**Comment by dlubitz** [comment] 2019-08-19 09:53
Didn't test it. But I guess so. Was just effecting the inline / shorthand Regex.

**Comment by janhelke** [comment] 2019-08-20 09:58
I have two more failing environments.

The current ddev environment (that might make it easy to reproduce and work on this issue)

Debian GNU/Linux 9 (stretch)
Linux version 4.9.184-linuxkit (root@a8c33e955a82) (gcc version 8.3.0 (Alpine 8.3.0) )
PHP 7.3.8-1+0~20190807.43+debian9~1.gbp7731bf (cli) (built: Aug  7 2019 19:46:25) ( NTS )

- Failing Site Configuration Edit and New
- Failing Reports module

One of our production environments

Gento
Linux version 4.14.127-gentoo (gcc version 7.3.0 (Gentoo 7.3.0-r3 p1.4))
PHP 7.3.6 (cli) (built: Jul 15 2019 16:26:07) ( ZTS )

- Failing TranslateViewHelper upon BE login

**Comment by lyxys** [comment] 2019-08-22 14:54
I could not reproduce the issue, but maybe my test setup was to simple. I used composer to get a TYPO3 installation and used the testcode posted by dlubitz above in the root of the webpage (after inserting <pre>$classLoader = require __DIR__ . '/../vendor/autoload.php';</pre> in front of it) to run the test from the command line on FreeBSD 11.2, php 7.3.8, pcre2 10.32_1. As output I get the "expected result". Could someone who has the problem try to reproduce it with this setup?

**Comment by lyxys** [comment] 2019-08-22 16:03
Well, after switching back to a slightly older environment, I CAN reproduce the problem with this small setup. Both environments have Freebsd 11.2-RELEASE-p9, but the failing environment has php 7.3.6 instead of 7.3.8 and pcre2 10.32 instead of 10.32_1. The difference between pcre2 10.32 and 10.32_1 appears to be that the former is linked against readline 7.0.5 while the latter is linked against readline 8.0.0. Maybe we can get the info about the used readline version for the other working and failing environments?

**Comment by alexanderschnitzler** [comment] 2019-08-25 12:45
Just adding a comment that I am struck by that issue as well on Ubuntu 19.04 with PHP 7.3.7 and PCRE 10.32, installed via brew.

**Comment by lyxys** [comment] 2019-08-26 08:58
> Just adding a comment that I am struck by that issue as well on Ubuntu 19.04 with PHP 7.3.7 and PCRE 10.32, installed via brew.

Can you check which version of readline your installation is using? Currently I suspect readline 7 to be the culprit, as the problem disappeared on FreeBSD after the pcre2 package switched to using readline 8.

**Comment by alexanderschnitzler** [comment] 2019-08-27 07:46
Well, I have different versions installed but I guess that while I installed PHP via brew, it uses the readline that is installed via brew as well:

```
$ brew info readline
readline: stable 8.0.0 (bottled)
Library for command-line editing
https://tiswww.case.edu/php/chet/readline/rltop.html
/home/linuxbrew/.linuxbrew/Cellar/readline/8.0.0_1 (48 files, 1.9MB) *
  Poured from bottle on 2019-08-09 at 17:29:54
From: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/readline.rb
==> Dependencies
Required: ncurses ✔
==> Analytics
install: 334,096 (30 days), 1,142,350 (90 days), 4,655,012 (365 days)
install_on_request: 27,414 (30 days), 104,308 (90 days), 459,949 (365 days)
build_error: 0 (30 days)
```

**Comment by robertvonhackwitz** [comment] 2019-08-27 13:47
Just FYI: same problem on this environment:
OS: CentOs 7.6
Http Server: httpd-2.4.6-89
Mysql: mysql-community-server-5.7.27-1
Php: php-7.3.8-1 (mod_php NOT php-fpm)

**Comment by smichaelsen** [comment] 2019-11-07 11:10
My suggestion is to change the order of if/elseif statements in the TemplateParser so the SubArray is built regardless of what other expression may or maynot have matched.
https://github.com/TYPO3/Fluid/pull/493

**Comment by smichaelsen** [comment] 2019-11-07 11:32
As a workaround the inline array can be wrapped in single quotes:
`{f:translate(id: 'some.id.to.translate', package: 'Vendor.Package', arguments: '{0: some.value}')}`

**Comment by dlubitz** [comment] 2019-11-07 11:33
This would solve the parser output in this case, but not the issue itself. But if it's the only way ATM to solve this, I would also go with that "hacky" solution.

**Comment by Konafets** [comment] 2019-11-07 11:37
@dlubitz A workaround never solves the problem, that’s why its called a "walk around" ;-)

**Comment by smichaelsen** [comment] 2019-11-07 11:55
From the tests within our team it does not look like it's readline or PCRE version related.

3 devs have identical versions:
readline: stable 8.0.1 (bottled) [keg-only]
PCRE Library Version => 10.32 2018-09-10

For 1 the TemplateParser works correctly, for 2 it doesn't.

**Comment by alexanderschnitzler** [comment] 2019-11-14 10:34
I am experiencing this bug yet again on a new (Cent OS) machine.

| PHP Version        | readline Version           | PCRE Library Version  |
| ------------- |-------------| -----|
| 7.3.10      | ? | 10.32 2018-09-10 |

**Comment by tmotyl** [comment] 2019-11-28 15:28
It would be nice if there were a single php file provided which can be run on different versions and which provides an pitput like:
- did array parsing worked
- what libraries versions are used
- what php version is used

This would ease testing

**Comment by NamelessCoder** [comment] 2019-11-28 18:21
@tmotyl This might help:

```php
<?php

$pattern = '/
		(?P<ArrayPart>                                                      # Start sub-match of one key and value pair
			(?P<Key>                                                        # The arry key
				 [a-zA-Z0-9_-]+                                             # Unquoted
				|"(?:\\\\"|[^"])+"                                          # Double quoted
				|\'(?:\\\\\'|[^\'])+\'                                      # Single quoted
			)
			\\s*[:=]\\s*                                                    # Key|Value delimiter : or =
			(?:                                                             # BEGIN Possible value options
				(?P<QuotedString>                                           # Quoted string
					 "(?:\\\\"|[^"])*"
					|\'(?:\\\\\'|[^\'])*\'
				)
				|(?P<VariableIdentifier>
					(?:(?=[^,{}\.]*[a-zA-Z])[a-zA-Z0-9_-]*)                 # variable identifiers must contain letters (otherwise they are hardcoded numbers)
					(?:\\.[a-zA-Z0-9_-]+)*                                  # but in sub key access only numbers are fine (foo.55)
				)
				|(?P<Number>[0-9]+(?:\\.[0-9]+)?)                           # A hardcoded Number (also possibly with decimals)
				|\\{\\s*(?P<Subarray>(?:(?P>ArrayPart)\\s*,?\\s*)+)\\s*\\}  # Another sub-array
			)                                                               # END possible value options
		)\\s*(?=\\z|,|\\})                                                  # An array part sub-match ends with either a comma, a closing curly bracket or end of string
	/x';

$template = 'foo: {bar: baz}';
$matches = [];
preg_match_all($pattern, $template, $matches);
if (empty($matches['Subarray'][0]) || $matches['Key'][0] !== 'foo') {
    echo 'FAILED';
    exit(1);
} else {
    echo 'OK';
}
```

**Comment by NamelessCoder** [comment] 2019-11-28 18:22
According to 3v4l.org, all versions of PHP since 7.1 support the pattern: https://3v4l.org/S98JI

**Comment by radmiraal** [comment] 2020-01-08 10:39
also ran into the bug (now in Neos) with the following sysinfo: https://gist.github.com/radmiraal/3e6b3143b413e0f31afa84618815d86c

**Comment by dlubitz** [comment] 2020-01-08 13:47
@NamelessCoder I'd like to provide a possible fix for this issue. What should be the target branch? 2.5 or master?

**Comment by NamelessCoder** [comment] 2020-01-08 13:55
@dlubitz `master` should be the target but before you do, would you mind if we discuss the potential fix? I suspect that https://github.com/dlubitz/Fluid/commit/ece2c4f8365fb6df57098e3fa6c5e0c55d82acc8 breaks nested variable notation like `{foo.{index}}`.

**Comment by dlubitz** [comment] 2020-01-08 14:00
Sure, lets discuss. I added another approach (#506) as the first try didn't solved the issue. I will add another test for the `{foo.{index}}` case.

**Comment by NamelessCoder** [comment] 2020-01-08 14:04
Let's continue in your pull request thread - big thanks for adding the tests btw.

**Comment by albe** [comment] 2020-01-08 16:46
After looking at this issue again and more closely, I do think the issue is with recursive matching on `Subarray`, which seems to write the recursive matches into the match placeholders on the affected systems, while it doesn't on the "expected" ones.

So `foo: { bar: baz }` will match `{ bar: baz }` as Subarray which in turn leads to a match of `Key = bar, ValueIdentifier = baz` - and for some reason the latter is written into the output matches, while the former isn't. I assume it only writes to empty matches then.

Compare https://gist.github.com/radmiraal/3e6b3143b413e0f31afa84618815d86c and e.g. https://travis-ci.com/smichaelsen/preg_php_tests/jobs/253941182

Now, given that a match on the `Subarray` part is the "most complex" match - if that exists, it should have precedence over other matches, so I'd go for the "turn the if/else around" solution.

**Comment by NamelessCoder** [comment] 2020-01-27 12:03
Patch https://github.com/TYPO3/Fluid/pull/493 merged even though I can't shake the feeling it's going to break some existing uses. At any rate, tests (both new and old) report it working on my test system.

Avaiting testing feedback before creating new releases.

**Closed by NamelessCoder** 2020-01-27 12:03 UTC

**Comment by alexanderschnitzler** [comment] 2020-01-30 16:14
Don't know if I said so before but I am actively using the patch on a live site for months now. It's a hotels website with a lot of traffic, no issues so far. :+1:
