### ISSUE TITLE
RFC: New conventional file extension depending on templated language

### ISSUE THREAD

**Issue by cedricziel** [TYPO3/Fluid#395] opened 2018-07-16 08:31 UTC
I've been working with [Twig](https://twig.symfony.com/) quite extensively and find it quite compelling to have both the template language AND the wrapped language in the filename.

Example:

```
base.html.twig
product_list.json.twig
feed.xml.twig
```

I'm currently developing an Open Source Plugin for the Fluid templating language for IDEA based IDEs (no release yet, will be fully open source) - and since Fluid is a language that is embedded in other languages, the lexing and parsing has multiple layers. Say one inner layer that is Fluid, surrounded by ordinary text and one outer layer that is the templated language (say html) consisting of the `text` tokens from the inner layer. So the decision, which language is in the outer layer is key, but it's important to also have a clear indicator of what is a fluid token and what is not.

Codifying both languages in the file name makes it several orders of magnitude easier to decide which, say `XML` files are also fluid templates. For both - machines and humans. Parsing a file in the hope it contains fluid tokens is the worst thing I can imagine.

While I won't hide the fact that most of the usage of the language happens in the TYPO3 CMS context and the template state can be inferred from the path (in MOST cases, not nearly all since it's configurable and could even be `fileadmin`), I think this would help anybody immediately associating a fluid template file with both the template language and the wrapped language.

I hereby propose a new file naming scheme:

```
filename.{wrapped language}.fluid
```

Examples:

```
Index.html.fluid
Feed.xml.fluid
PublicPosts.atom.fluid
Nightmare.json.fluid
```

## Impact:

The file locator would be adjusted to search for `.fluid` files first, then chain-load `.html` files for backwards compatibility.

For environments where additional loaders are added (looking at TYPO3 CMS f.e.), the impact is minimal, but could transition gradually to the new pattern.

### Pro:

* the file type is more recognizable to external tools, foremost IDEs and editors with syntax highlighting. - They could highlight more easily since it's immediately clear what languages are present
* reduces headaches since ordinary language files (html, json), are more distinguishable from templates

## Con:

* ?

<hr>

I'm looking forward to discussing the matter with you.

**Comment by sascha-egerer** [comment] 2018-07-16 08:56
I'm against that. 
Fluid-HTML files container valid HTML syntax. Thats one of the main benefits of Fluid.
If you want something like that you can name your files `Index.fluid.html`. I don't see a reason the put the `fluid` at the end of the filename and destroy support of all IDE's as they don't know how to handle the file anymore.

**Comment by tantegerda1** [comment] 2018-07-16 09:59
1. No, that would lead you to a `Contact.fluid.vcf` and a `Product.fluid.json`, both easily identified by editors.

**Comment by cedricziel** [comment] 2018-07-16 10:08
A language identifier in a suffix of the filename / prefix of the extension would serve the same purpose and it's equally useful.

The question stays the same - is it worth communicating this as an "official" naming scheme and adapt the loaders to prefer those files?

**Comment by NamelessCoder** [comment] 2018-07-16 10:55
If I may chip in here. The purpose of the `.twig` file extension seems to be detection. For example, PHPStorm somehow detects these as special twig files. So that seems to be our premise: detection, secondarily separating multiple template engines storing files in the same folder.

With that in mind, I personally think it's the wrong decision to choose a new file extension, thus invalidating the fact that Fluid files are intended to "be" the same format as the markup they contain. As @sascha-egerer says, one benefit of Fluid is that it's XML-based and works seamlessly in such files. You can even validate them with schema.

Changing the file extension would disrupt this rather important aspect.

On the other hand, adding a suffix between the filename and extension has no problems associated with it. It's a breaking change if you do (because either the format is different or the lookup process is different) but it's possible to do. I would do it, personally - because I think it's far too much moving of important bits, for the mere purpose of detecting a file as containing (X)HTML plus Fluid rather than just (X)HTML.

So I have to say no - I don't think it's a good idea to change this. And I also don't think it's a good idea to change how we communicate the naming scheme, since you face other trouble if all of your template files suddenly have to be invoked with for example `<f:render partial="MyPartial.fluid" />`.

PS: the template resolving logic is already a performance bottleneck with several problems attached to it, among other things, it needs to resolve files before it can determine if they are cached. If we add more lookups here, I think we risk compounding that problem.

**Comment by cedricziel** [comment] 2018-07-16 11:08
Thank you, Claus. I can accept if the proposal is rejected - no problem.

I see no problem with having to reference a full name from the search paths: `<f:render partial="MyPartial.fluid.html" />`

A question that arises immediately, is if intrinsic problems of the language should have direct effects on the filesystem level.

That leaves me with more questions than I initially had :)

1. the template-resolving: once compiled, shouldn't it be static?
2. if true, having loose identifiers for template references such as `Default` doesn't seem to be a good then at all :) (it could still coerce the format)

**Comment by mbrodala** [comment] 2018-07-16 11:09
Notice that this can be used already:

    <f:render partial="MyPartial.fluid.html" />

In this case Fluid recognizes the explicit format and uses this instead of the one e.g. derived from the current request.

**Closed** 2018-07-16 11:09 UTC

**Comment by NamelessCoder** [comment] 2018-07-16 11:23
> A question that arises immediately, is if intrinsic problems of the language should have direct effects on the filesystem level.

That is a very good question. Of course we tend to say no, it shouldn't. But we do have to consider the reality of the current state of the resolving logic. You could see it as a "we're blocked by that" sort of input from me - it just means we are not completely free to move things around, at least until we do some other things first.

> the template-resolving: once compiled, shouldn't it be static?

He asks, which is the perfect question!

> if true, having loose identifiers for template references such as Default doesn't seem to be a good then at all :) (it could still coerce the format)

That's not the root cause for the problem. But I know what is, and I may have a way to solve it.

Current behavior is to receive the requested identifier, then look for it in all paths, then determine if that file was previously compiled, then returning either the parsing state (that then may be compiled) or the compiled template.

It is done this way because the template paths may change during runtime - but the absolute path of the template does not.

So perhaps a better way is to hash the root paths or various types that we receive. Then, when compiling files, compile them not by the file identifier but by the root paths hash plus local file identifier.

This would allow the resolving logic to immediately look for a given template in compiled state (by class name alone). But it also means that the same template may be compiled many times over, in all combinations of the different root paths and not least priorities of paths that you pass.

Just thinking out loud. To be honest, I'm not sure what would cost the most... and the actual benefit completely depends on the setup (because most tend to use one or two paths for each group of templates). The resolved template does get cached in runtime, so multiple calls to render the same partial from the same plugin/request/view won't have to resolve it twice.

**Comment by cedricziel** [comment] 2018-07-16 11:37
@mbrodala thanks for the hint. It's not so much about my personal usage of the language but I would rather like a general guideline for this.

From a tooling perspective, the file type is derived from the extension. If the extension is html, then the content is html. It's not html with fluid, it's html. If it's xml, then the content is xml - not xml with fluid.

When deriving a file type from it's location, everything is fine as long as the path is `Resources/Private/{Templates|Layouts|Partials}`. What about files in `fileadmin/my_site_templates/html` or `Resources/Private/Plugins/news/Templates` or in a standalone project?

IMHO a files' content type should be reflected by its filename. Currently this is not the case.

@NamelessCoder thanks for the explanation. To reiterate on the template resolving, we could measure whether another file system call is really something, we can consider a bottleneck (https://github.com/TYPO3/Fluid/blob/master/src/View/TemplatePaths.php#L721). If it is, this problem deserves some additional attention anyways :)

Anyways. I have closed the issue since it doenst "seem to be a good fit", currently.

**Comment by NamelessCoder** [comment] 2018-07-16 11:50
I don't think a few more calls to is_file() which I think compiles to a single opcode operation around a system call - and I wouldn't mind seeing a PR that adds `Filename.fluid.html` as a supported filename. If this comes after the more generic version, even less cause to worry as far as I am concerned.

The parts I don't think we should be doing:

1. Make that naming the new convention. At the very, very least it has to be tested in the wild and some sort of consensus reached (also with the Neos team). That's why I'd put this lookup after the one that's just filename + format, but before the one that looks for it without adding format as extension.
2. Change the extension itself to `.fluid` - again, I wouldn't object to adding this as a lookup as long as it comes after the standard one.

In both cases I think these are both too drastic to adopt as convention right away. We can however take it slowly and make it possible, then use your IDE plugin and other agnostic tools as good examples of why it might be a good idea to adopt a new convention. At some point, at some time.

So don't abandon this just yet. But do it with baby steps ;)
