### ISSUE TITLE
Ternary expression and cache seems to result in wrong result on second and consequent calls

### ISSUE THREAD

**Issue by AndreasA** [TYPO3/Fluid#203] opened 2016-10-19 08:06 UTC
When using current GIT master of typo3/cms and using Ternary expression then when using it like this:
{settings.false ? 'foo' : 'bar'}

And having set:
settings.false = 0

Then the result is that on the first call it results in 'bar' as output.
On the second and consequent calls it results in 'foo'

When putting the terenary expresion inside f:cache.disable:
<f:cache.disable>{settings.false ? 'foo' : 'bar'}/f:cache.disable

then it always results in 'bar'.

Add the FluidTemplate via typoscript directly and the settings like this:
10 = FLUIDTEMPLATE
10.file = PATH-TO-FILE.html
10.settings.false = 0

I have the same issue with using 10.variables instead of settings.

Might be realted to #148

**Comment by NamelessCoder** [comment] 2016-10-21 22:26
Is very likely related to #148. If you can, please debug this to see if the compiled template causes an incorrect variable access, e.g. attempting to directly access an object as an array or similar.

**Comment by AndreasA** [comment] 2016-10-26 11:20
I will check it, if I have time on Friday (not sure if I will have the time though).

**Comment by AndreasA** [comment] 2016-10-27 06:01
I have debugged it now and the issue is not the variable access but in the compile method the compiledExpression is not generated correctly.

`$compiledExpression = $parser->compile($check);`

$check is in my case: 'settings.false', it doesn't contain the "{" and "}" which results in the compiledExpression being a string instead of `$context['settings.false']`

**Comment by AndreasA** [comment] 2016-12-09 12:22
Any news in that regard?

**Comment by christoph-bessei** [comment] 2017-06-10 14:45
@AndreasA Did you find a workaround for this issue? I have the same problem at the moment.

**Comment by AndreasA** [comment] 2017-06-12 18:18
Haven't tried this again sicne I reported the issue.
It probably still exists.

**Comment by NamelessCoder** [comment] 2017-06-13 10:59
Closing as duplicate of #212 even though this issue came first - #212 deals with the exact reason for this problem.

**Closed by NamelessCoder** 2017-06-13 10:59 UTC

**Comment by christoph-bessei** [comment] 2017-06-13 11:05
@NamelessCoder Is this really a duplicate? I have also caching problems when I use only variables (which I created with f:alias before). Maybe related to #300?

**Comment by NamelessCoder** [comment] 2017-06-13 11:33
This issue is indeed a duplicate of #212. The issue reported in #300 is related and potentially caused by the same function but could also be an issue with `f:alias` so we keep that open.
