### ISSUE TITLE
Fluid xmlns declaration silently fails if using https

### ISSUE THREAD

**Issue by georgringer** [TYPO3/Fluid#385] opened 2018-05-16 05:59 UTC
Currently fluid just checks `http://typo3.org/ns' in `NamespaceDetectionTemplateProcessor` with 
```
if (strpos($namespaceUrl, 'http://typo3.org/ns/') === 0) {
    $namespaceUri = substr($namespaceUrl, 20);
    $namespacePhp = str_replace('/', '\\', $namespaceUri);
} elseif (!preg_match('/([^a-z0-9_\\\\]+)/i', $namespaceUrl)) {
    $namespacePhp = $namespaceUrl;
    $namespacePhp = preg_replace('/\\\\{2,}/', '\\', $namespacePhp);
} else {
    $namespacePhp = null;
}
```

It should also allow `https://typo3.org/ns``
This issue is a copy of https://forge.typo3.org/issues/85018

**Comment by NamelessCoder** [comment] 2018-05-16 07:53
I'm afraid this is a misunderstanding (see PR thread). The schema has only one identifier. Allowing it to have a secondary identifier with https will merely confuse an IDE because the schema no longer contains the same ID as your import. Keep in mind that the xmlns-style imports have a meaning both in Fluid and generally as XML!

**Comment by sascha-egerer** [comment] 2018-05-16 07:58
As already said the namespace is a case sensitive identifier. This change does not really make sense.
See also https://www.w3.org/TR/2009/REC-xml-names-20091208/#NSNameComparison

**Comment by webloft** [comment] 2018-05-16 11:03
It may be fine that namespace is case sensitve - but it should not silently ignore anything.

**Comment by webloft** [comment] 2018-05-16 11:41
OK. But using a different scheme does not change the actual URI in my sight even it is not a goal to support multiple schemes. Its a more a logic thing - like forward non-www to www-address. If the URI contains the token //typo3.org/ns/ it should be clear that a PHP namespace should be used and the problem is gone - any points against?

**Comment by NamelessCoder** [comment] 2018-05-16 12:31
> any points against?

Absolutely there are points against. At the core of the issue is the fact that this isn't a URI, it is an ID. We do not allow "loose" IDs anywhere - that would add to the confusion, not prevent it. They *must* be unique and there *must* exist only one ID for each namespace.

This doesn't only relate to the PHP namespaces. It's also about identifying XSD files - the schema isn't something we invented and we have to follow the rules for implementing it. It's easy to get tunnel vision and look at only the xmlns-to-PHP relationship of Fluid, but it actually builds on well defined standards that impose this ID pragma.

If you're interested in those you can read my reply here: https://github.com/TYPO3/Fluid/pull/360#issuecomment-353579429.

**Comment by webloft** [comment] 2018-05-16 13:05
> It's easy to get tunnel vision.
I agree - but it is hard to debug If you don't look for that - because Fluid throws errors even if you call an invalid argument and looks very strict.

But besides the XML-Syntax, the inline-notation responds with NULL too - at least there should be warning that the prefix cannot be resolved to a viewhelper?

**Comment by NamelessCoder** [comment] 2018-05-16 13:33
> I agree - but it is hard to debug If you don't look for that

It *is* hard to debug when you write a typo (which this is semantically the same as) in a namespace identifier. Why? Because it _makes Fluid ignore that namespace_ if the typo is in the prefix part that we're matching.

If the typo is in the vendor/namespace part, you see an error. But only if 1) it is not an extended namespace or 2) the VH you try to resolve doesn't exist in any of the compound PHP namespaces.

I don't know how else to explain the problem of this particular and very edge use case, where someone causes the `f:` namespace to become ignored, then uses inline syntax to reach this exact piece of code which has no way to return the original representation.

https://github.com/TYPO3/Fluid/blob/master/src/Core/Parser/TemplateParser.php#L358

There is no way to output the untouched original expression, and even if there were, it would be inconsistent to do so if for example you used a variable reference inside this inline piece. How much of the expression should be evaluated? What if you used a value that can't be expressed as string and receive a fatal error? Given that Fluid will parse the entire expression you wrote, how is it supposed to know what should come out on the other side when you call an ignored namespace with inline syntax? Returning NULL may seem like a cop-out, but nothing else would be sensible since Fluid is not capable of keeping the original source code for an entire inline expression - which is the only sensible alternative if you ask me (but even that comes with hard-to-debug consequences).

I invite you to take a look deeper into the source code to understand what an ignored/invalid namespace means to the parser. This is what is happening inside Fluid when you misconfigure a namespace like this. It gets ignored, because for all we know, _it was intentional that the namespace shouldn't be considered a Fluid/PHP namespace_. Which brings us back to the core of the issue: this ID is very fixed and we can't process any other variants than the one that is the true ID. Everything else *has* to be taken naively as intentional by the user.

**Comment by NamelessCoder** [comment] 2018-05-16 20:52
I am completely aware of the problem and all the implications. In case you didn't know, I actually wrote the code that handles this. You're making a few assumptions that don't take into account the information I gave above. For one, inside the parser, both tag and inline syntax can yield a ViewHelperNode, but only one of those is possible to handle in a predictable manner - which I tried to illustrate with the series of questions that the parser would naturally face.

You *have* to remember that an ignored namespace means 1) tag mode outputs raw and 2) inline syntax always gets nulled, and 3) using an ignored namespace in inline syntax poses a dilemma between throwing an error about something that the developer explicitly asked to be ignored, or return null to avoid possible side issues. Both can be argued as equally unexpected but only one of them semantically corresponds to "ignoring" the expression. An error is the direct opposite of ignoring.

We've gone far off track now in discussing an edge case that happens because of incorrect/accidental usage of an established feature (ignore third party NS) so I'm not really sure what we hope to achieve? After all, this happens so infrequently that it has been almost six months since the last time this question was even asked and that time it was only indirectly related. It doesn't seem to be a really big problem out in the wild...

Can you imagine, all of this discussion started with a single letter `s`?

**Comment by webloft** [comment] 2018-05-16 21:35
Hmm.. Why should the developer explicity ask to ignore the inline notation? Its Fluid only - thus it should be executed by Fluid extended viewhelpers and should do something and throw an error if it was not able to. End of story. As a developer I would expect that and if I want to exclude some string from being parsed I need to use an escape sequence like everywhere else...

I only get the information that I can abuse the inline notation with a dummy expression as a comment since it gets not really executed - like writing in /dev/null. And it is incosistent because the prefix is declared in head - if Fluid parses the expression and the prefix is used in the expression there is no question that a viewhelper must be called and therefore there should be an error. Software should things make easier, not harder.

But you are right it is a litte bit offtopic to this issue.

> It doesn't seem to be a really big problem out in the wild...
Yeah, that's the way Microsoft goes... till it is ;)

**Comment by NamelessCoder** [comment] 2018-05-16 21:52
> there is no question that a viewhelper must be called and therefore there should be an error.

Except that the prefix that was registered is explicitly designed to ignore the namespace which means there is no question that a ViewHelper must not be called because one would never be resolved.

I don't know how else to say it. If you ignore something, then obviously it isn't going to cause correct resolving of a ViewHelper and can't throw an error about a ViewHelper. It doesn't matter if something is "Fluid only" in terms of syntax - once converted to a syntax tree, there is literally no difference.

The reason I have not invited you to create a PR for this is simply that I don't want to see you wasting your time. Many years of experience and being a key person in the development of Fluid has left me with the very clear conviction that ignoring of namespaces is done in the most sensible way we can: ignored means ignored and something that's ignored will never cause an error; it may even be suppressed to prevent an error. But if you insist that I'm wrong in this conviction, by all means, do demonstrate what you would see as an improvement, by making a PR that others can also analyse instead of this theoretical trip down the rabbit hole with me ;)

I don't mind taking such discussions but I think it might be time that you find out for yourself if I'm right or wrong. Seems I can't convince you with words so a trip into the code might do it.

**Comment by NamelessCoder** [comment] 2018-05-16 21:56
Also, you can trust me that if we suddenly get this same question multiple times a week, it's going up in bent neon in the most central place I can think of, in huge blinking red letters. It really is as rarely asked as I described above.

**Comment by NamelessCoder** [comment] 2019-06-03 13:20
Closed with same reason as https://github.com/TYPO3/Fluid/pull/360.

**Closed by NamelessCoder** 2019-06-03 13:20 UTC
