### ISSUE TITLE
Performance Tests

### ISSUE THREAD

**Issue by mneuhaus** [TYPO3/Fluid#64] opened 2016-01-22 22:38 UTC
As initially found by christian there is a performance hit compare to the typo3cms/fluid variant, which results in some cases in a almost doubled rendering time.

the main issue seems that most viewHelpers reverted to non static variants, so lets fix that :) 

**todo**:
- we'll make render optional by making it an automatic call to renderStatic with `$this->arguments`
- make every standalone viewHelper static or compiled
- maybe reintroduce viewHelperInstance reusing

cc @NamelessCoder @helhum @lolli42 
related: https://review.typo3.org/#/c/42425/112

**Comment by NamelessCoder** [comment] 2016-01-23 00:52
Some feedback after discussing the issue (in moderate detail so far) and testing on PHP 7.0.1.

I've identified the following possible improvements to the compiled rendering process and have ranked them as follows:

## Compile method and compiled behavior (impact: 100%)

Obviously, the beats-all option is to implement compile() methods on all ViewHelpers. However, that simply works around the issue - which is essentially that in order for all ViewHelpers to automatically become compilable a conscious trade-off was made, allowing *some* ViewHelpers to become instantiated on-the-fly even when compiled. A fallback solution was implemented which uses the ViewHelperResolver also in compiled templates. The intention being that performance would be acceptable although obviously far from ideal.

This decision was incorrectly induced - it turns out that due to the way templates are compiled, significant processing time now has to be spent on creating instances, fitting them with a context, validating arguments and so on. The issue is made even more pronounced by third-party ViewHelpers (without compile() methods) are wide-spread and would all use the fallback implementation.

The fallback implementation is as such identified as the main cause of performance decrease in compiled templates. The following will deal with options to improve this implementation and can be implemented individually or combined.

## Instance reuse, compiled (impact: ~25%)

This one could be a whopper in terms of performance: if compiled template classes would become aware of which ViewHelper classes were used which rely on the fallback implementation when compiled, an initialisation and local caching of instances could be performed. This would skip several function calls in every iteration of every loop, every rendering of a section and so on.

It's quite hard to estimate the impact of this but I have placed it around 25% even though templates which only use core ViewHelpers would gain no perceivable performance boost. Templates with many loops and heavy use of third-party ViewHelpers might experience even more impact.

**TYPO3 relevancy**

This issue is particularly relevant for TYPO3 since every ViewHelper provided by this framework uses dependency injection which needs to be triggered on every instance creation. A custom ViewHelperResolver already exists which is easily adapted to cache instances.

## Instance reuse, general (impact: ~15%)

Depending on which ViewHelpers are being used (how complex they are to initialise) significant improvement can be made by storing instances of ViewHelpers in transient memory cache (tested with L1 caching in ViewHelperResolver) which avoids creating new instances. Such behavior is not decided by Fluid itself in order to not impose any decisions on consumers, but can easily be implemented in a custom ViewHelperResolver.

The choice to not impose any decisions on the consumer *can* be reversed: we could make a decision that by default, ViewHelperResolvers *will* cache instances in memory and not make new instances - and require consumers to "undo" such caching by overriding this behavior with a custom ViewHelperResolver.

A feature for Fluid itself to toggle this does not seem like a wise choice given that such a toggle would have to be repeatedly checked (and might impose an interface change which would not be desired).

**TYPO3 relevancy**

Instance reuse in this context has the same relevancy as instance reuse in compiled templates with one small difference: impact is not as significant with general instance reuse as it would be with instance reuse in compiled templates as described above.

## Argument validation extracted (impact: ~5%)

We might consider a modification to the evaluation and validation of arguments - Fluid was changed to refactor argument validation *outside* of the ViewHelper as a way to provide a single point to manipulate this behavior.

However, once compiled, argument validation can be a bit more selective. It could improve performance if we were to receive a bit more info about the compiled arguments array before validating and assigning it; for example whether or not the array contains undeclared arguments that require additional validation. Including this in the compiled state and passing it to argument validation will allow circumventing some loop-based operations which would become costly in templates with big loops using many ViewHelpers.

The impact of this change is less significant as argument validation is fairly straight-forward and self-contained; optimisations would primarily come because this concerns code that must run before any and every ViewHelper unless it implements a custom compile() method.

**TYPO3 relevancy**

There is no particular relevancy for TYPO3 regarding this optimisation. TYPO3 would benefit as much as any other framework and would not be adversely affected in any way.

## Conclusion

We should be able to almost immediately shave off approximately 30-40% of the performance drain caused by the sub-optimal fallback rendering implementation in compiled templates with another couple of percent being readily available through refactoring argument validation. Instance reuse in compiled templates would be the most significant change as it approximates the way uncompilable ViewHelpers worked in the SyntaxTree; preserving an "uninitialised" instance which could be initialised fully by providing arguments, child nodes and so on. We would be able to replicate this by storing "uninitialised" instances and passing them the arguments array and a renderChildClosure which should come pretty close to performing like they would if you disabled the template compiler entirely (like it would be done by the template parser in earlier Fluid versions when encountering ViewHelpers that did not implement the compilable interface or implemented the child node access interface).

I'm sure these are far from the only options we have - just the results of an hour or two of testing and relating those results to earlier considerations about the admittedly poor fallback rendering implementation for compiled templates.

**Comment by lolli42** [comment] 2016-01-23 11:50
For the instance re-usage: I'd heavily recommend to stay away from that. Making VH's pseudo singletons doesn't help but opens a large pit hole of possible issues if a dev doesn't understand the impact and its possible side effects: A single VH either has state (then a fresh instance per call is required) or it doesn't (then it provides a static method that is called). This already isn't trivial for everyone to understand. If something in between is introduced (not static, but class re-usage with maybe a cleanup method, done just because our injection is so expensive?) will catapult the complexity of the VH implementation and i'd bet we'd see tons of not-so-funny issues like "hey, i have a bug i don't understand if i insert the same element a second time on the page". Also keep in mind that often VH's are coded by people who are not really that deep in the system. Do not do that, keep it simple.

**Comment by NamelessCoder** [comment] 2016-01-23 13:44
Instance reuse as described above would not turn ViewHelpers into singletons. It would mimic the way TYPO3 ViewHelpers are currently rendered when the template cannot be compiled. If I did not make that clear enough then I apologise for that - it's a key aspect of the solution I proposed.

https://git.typo3.org/Packages/TYPO3.CMS.git/blob/HEAD:/typo3/sysext/fluid/Classes/Core/Parser/SyntaxTree/ViewHelperNode.php#l54

As you see here, ViewHelperNodes are created with an uninitialised ViewHelper instance kept in storage; this instance is then used and initialised when the ViewHelperNode gets evaluated. The same would be the point of the solution I propose: to keep these instances in a way that mimics the instance reuse that already goes on in TYPO3 Fluid. They are already semi-singletons when used in uncompilable templates.

I'd like to stress that this is a decision that was intentionally undone in standalone Fluid exactly to avoid a singleton-like behavior of previously uncompilable ViewHelpers when used in a compiled template. The solution would have to somehow be aware of that and only use the uninitialised instance once per compiled ViewHelperNode *but avoid creating a new instance every time the section/closure it is contained within gets executed*.

Instance reuse may have been a bad heading for that but hopefully this describes what currently is in TYPO3, how that differs from standalone Fluid and why I included it as a possible solution.

There is another way though. Rather than let Fluid compile templates which contain ViewHelpers that do not provide a custom renderStatic method it is possible to override the default compile() method with one that simply disables the template compiler - thus completely restoring the previous behavior where templates in which uncompilable ViewHelpers were used, would never be compiled to PHP. It is unknown what this change would do in terms of performance but I can certainly make a test.

**Comment by NamelessCoder** [comment] 2016-01-23 14:56
I will have a few more testing results in a little while. So far I've managed to bring the performance within 80% of an unmodified TYPO3 master with the same database (without including any of the previous suggestions).

**Comment by mneuhaus** [comment] 2017-01-17 07:02
@NamelessCoder i think we can archive this one, right?

**Comment by NamelessCoder** [comment] 2017-01-17 08:58
I think we can close this one, yes. At some point I will do more profiling, but at the current time, there's no pressing need for it.

**Closed by NamelessCoder** 2017-01-17 08:58 UTC
