### ISSUE TITLE
Cannot render optional sections with inline notation

### ISSUE THREAD

**Issue by mbrodala** [TYPO3/Fluid#290] opened 2017-05-18 10:27 UTC
It seems like there is a difference when rendering optional sections in the regular and the inline notation.

Given the following two layouts:

- `layouts/Regular.html`
  ```xml
  <f:render section="Main"/>
  <f:render section="Missing" optional="true"/>
  ```
- `layouts/Inline.html`
  ```xml
  <f:render section="Main"/>
  {f:render(section: 'Missing', optional: true)}
  ```

And the following two templates:

- `regular.html`
  ```xml
  <f:layout name="Regular"/>
  <f:section name="Main">First</f:section>
  ```
- `inline.html`
  ```xml
  <f:layout name="Inline"/>
  <f:section name="Main">First</f:section>
  ```

If you render the template using the regular layout it works as expected:

```
$ bin/fluid --layoutRootPaths layouts --template regular.html 
First

```

However, the template using the inline layout fails:

```
$ bin/fluid --layoutRootPaths layouts --template inline.html 
PHP Fatal error:  Uncaught TYPO3Fluid\Fluid\View\Exception\InvalidSectionException: Section "Missing" does not exist. in /.../vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php:253
Stack trace:
#0 /.../vendor/typo3fluid/fluid/src/ViewHelpers/RenderViewHelper.php(139): TYPO3Fluid\Fluid\View\AbstractTemplateView->renderSection('Missing', Array, false)
#1 [internal function]: TYPO3Fluid\Fluid\ViewHelpers\RenderViewHelper->render()
#2 /.../vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(256): call_user_func(Array)
#3 /.../vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(245): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->callRenderMethod()
#4 /.../vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(78): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->initializeArgumentsAndRender()
#5 /.../vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(153): TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInvoker->invoke(Object(TYPO3Fluid in /.../vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php on line 253

Fatal error: Uncaught TYPO3Fluid\Fluid\View\Exception\InvalidSectionException: Section "Missing" does not exist. in /.../vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php:253
Stack trace:
#0 /.../vendor/typo3fluid/fluid/src/ViewHelpers/RenderViewHelper.php(139): TYPO3Fluid\Fluid\View\AbstractTemplateView->renderSection('Missing', Array, false)
#1 [internal function]: TYPO3Fluid\Fluid\ViewHelpers\RenderViewHelper->render()
#2 /.../vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(256): call_user_func(Array)
#3 /.../vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(245): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->callRenderMethod()
#4 /.../vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(78): TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->initializeArgumentsAndRender()
#5 /.../vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(153): TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInvoker->invoke(Object(TYPO3Fluid in /.../vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php on line 253
```

**Comment by mbrodala** [comment] 2017-05-18 10:40
The issue seems to be the `optional: true` which is different from `optional="true"`. The former evaluates to a missing variable thus empty value, the latter evaluates to the string `"true"`. Because of this the rendering with inline notation causes the section to not be optional but working fine with the regular notation.

The fix is to use `optional: 1` (and `optional="1"` for consistency).

I wonder if the variables `true` and `false` should be reserved however and always have their fixed boolean values.

**Comment by sascha-egerer** [comment] 2017-05-18 16:20
Is that related to #253 ?

**Comment by NamelessCoder** [comment] 2017-05-18 16:34
Not related to https://github.com/TYPO3/Fluid/issues/253 but indirectly related to https://github.com/TYPO3/Fluid/issues/127. The problem is that `{true}` is not a template variable so we have to pass integers instead (or manually add a template variable named `'true'` with a value of `(bool)true`.

Closing the issue since this works by design - and the only way to report this particular problem would be to report failure to resolve variables, which would cause a heap of other trouble.

I will however very closely consider this case for the [Fluid Linting tool](https://github.com/TYPO3/Fluid.Lint), to discover potential problems with variables that aren't assigned + inspections for node hierarchy that would let you find that this is an ObjectAccessor returning null rather than a hardcoded boolean value.

**Closed by NamelessCoder** 2017-05-18 16:34 UTC
